version: 6.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
init:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
install:
  - choco install redis-64
  - redis-server --service-install
  - redis-server --service-start
before_build:
  - cmd: nuget restore
build:
  project: StackExchange.Redis.Extensions.sln
  verbosity: minimal
test_script:
  - cmd: dotnet test -f:netcoreapp3.1
