on:
  push:
    branches:
      - v6
    tags:
      - "*.*.*"
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Dependencies (Ubuntu)
        #uses: zhulik/redis-action@1.1.0
        run: sudo apt install redis-server
        if: matrix.os == 'ubuntu-latest'

      - name: Install Dependencies (Windows)
        run: choco install redis
        if: matrix.os == 'windows-latest'

      - name: Install Dependencies (macOS)
        run: brew install redis
        if: matrix.os == 'macos-latest'

      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - run: dotnet --info
      - if: contains(matrix.runs-on, 'macOS') || contains(matrix.runs-on, 'ubuntu')
        run: ./build.sh

      - if: contains(matrix.runs-on, 'windows')
        run: ./build.cmd
