on:
  push:
    branches:
      - v6
    tags:
      - "*.*.*"
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Install Dependencies (Ubuntu)
        uses: zhulik/redis-action@1.1.0
        if: matrix.runs-on == 'ubuntu'

      - name: Install Dependencies (Windows)
        run: choco install redis
        if: matrix.runs-on == 'windows'

      - name: Install Dependencies (macOS)
        run: brew install redis
        if: matrix.os == 'macos'

      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - run: dotnet --info
      - if: contains(matrix.runs-on, 'macOS') || contains(matrix.runs-on, 'ubuntu')
        run: ./build.sh

      - if: contains(matrix.runs-on, 'windows')
        run: ./build.cmd
