name: StackExchange.Redis.Extensions Build
on:
  push:
    branches:
      - v9

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest"]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Dependencies (Ubuntu)
        run: sudo apt install redis-server
        if: matrix.os == 'ubuntu-latest'

      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - uses: actions/checkout@v2
      - name: Setup .NET Core6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - uses: actions/checkout@v2
      - name: Setup .NET Core7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - run: dotnet --info
      - if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: ./build.sh
