name: StackExchange.Redis.Extensions Build
on:
  push:
    branches:
      - v9

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Environment variable used by the `client.js` script to create a new Redis client.
    env:
      # The hostname used to communicate with the Redis service container
      REDIS_HOST: redis

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x

      - name: Setup .NET Core 6.0
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 6.0.x

      - name: Setup .NET Core 7.0
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 7.0.x

      - name: Build with dotnet
        run: dotnet test
        shell: bash

  publish:
    needs: container-job
    name: Publish Nuget Packages
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x

      - name: Setup .NET Core 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Setup .NET Core 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build with dotnet
        run: ./NuGetPack.bat
        shell: bash
